name: Deploy production IAC changes

on:
  push:
    branches:
      - 'main'
    paths:
      - 'environments/prd/**'
      - 'terraform/**'
      - 'pipelines/iac/common.conf'
      - 'pipelines/iac/prd.conf'
      - '.github/workflows/iac-prd-push.yml'

jobs:

  pipeline-cd:

    runs-on: ubuntu-latest
    env:
      ENGINE_ENV       : prd
    steps:

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true

      - uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.7
          terraform_wrapper: false

      - name: deploy-changes
        shell: bash
        run: |
          make -C "$GITHUB_WORKSPACE"/pipelines/iac cd
